# Generated by Django 2.2.2 on 2021-04-29 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('manufacturer', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('EO', 'Electronics & Office'), ('CS', 'Clothing, Shoes & Accessories'), ('HF', 'Home, Furniture & Appliances'), ('TG', 'Toys, Games, and Video Games'), ('HI', 'Home Improvement'), ('MM', 'Movies, Music & Books'), ('BA', 'Baby'), ('PA', 'Patio & Garden'), ('FO', 'Food, Household & Pets'), ('PH', 'Pharmacy, Health & Personal Care'), ('BE', 'Beauty'), ('SP', 'Sports, Fitness & Outdoors'), ('AU', 'Auto, Tires & Industrial'), ('PP', 'Photo & Personalized Shop'), ('AC', 'Art, Craft, Sewing & Party Supplies')], max_length=2)),
                ('code', models.CharField(default=None, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('specifications', models.TextField(max_length=9999)),
                ('stock', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('barcode_num', models.IntegerField(unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
