# Generated by Django 2.2.2 on 2021-05-08 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Electronics & Office', 'Electronics & Office'), ('Clothing, Shoes & Accessories', 'Clothing, Shoes & Accessories'), ('Home, Furniture & Appliances', 'Home, Furniture & Appliances'), ('Toys, Games, and Video Games', 'Toys, Games, and Video Games'), ('Home Improvement', 'Home Improvement'), ('Movies, Music & Books', 'Movies, Music & Books'), ('Baby', 'Baby'), ('Patio & Garden', 'Patio & Garden'), ('Food, Household & Pets', 'Food, Household & Pets'), ('Pharmacy, Health & Personal Care', 'Pharmacy, Health & Personal Care'), ('Beauty', 'Beauty'), ('Sports, Fitness & Outdoors', 'Sports, Fitness & Outdoors'), ('Auto, Tires & Industrial', 'Auto, Tires & Industrial'), ('Photo & Personalized Shop', 'Photo & Personalized Shop'), ('Art, Craft, Sewing & Party Supplies', 'Art, Craft, Sewing & Party Supplies')], max_length=40)),
                ('model', models.CharField(max_length=80, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
