# Generated by Django 2.2.2 on 2021-04-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210429_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics & Office', 'Electronics & Office'), ('Clothing, Shoes & Accessories', 'Clothing, Shoes & Accessories'), ('Home, Furniture & Appliances', 'Home, Furniture & Appliances'), ('Toys, Games, and Video Games', 'Toys, Games, and Video Games'), ('Home Improvement', 'Home Improvement'), ('Movies, Music & Books', 'Movies, Music & Books'), ('Baby', 'Baby'), ('Patio & Garden', 'Patio & Garden'), ('Food, Household & Pets', 'Food, Household & Pets'), ('Pharmacy, Health & Personal Care', 'Pharmacy, Health & Personal Care'), ('Beauty', 'Beauty'), ('Sports, Fitness & Outdoors', 'Sports, Fitness & Outdoors'), ('Auto, Tires & Industrial', 'Auto, Tires & Industrial'), ('Photo & Personalized Shop', 'Photo & Personalized Shop'), ('Art, Craft, Sewing & Party Supplies', 'Art, Craft, Sewing & Party Supplies')], max_length=40),
        ),
    ]
