# Generated by Django 2.2.2 on 2021-04-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210429_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='barcode_num',
            new_name='barcode',
        ),
    ]
