# Generated by Django 2.2.2 on 2021-05-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('doc_id', models.IntegerField()),
                ('address', models.CharField(max_length=80)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('phone', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
