CATEGORIES = [
    ("Electronics & Office", "Electronics & Office"),
    ("Clothing, Shoes & Accessories", "Clothing, Shoes & Accessories"),
    ("Home, Furniture & Appliances", "Home, Furniture & Appliances"),
    ("Toys, Games, and Video Games", "Toys, Games, and Video Games"),
    ("Home Improvement", "Home Improvement"),
    ("Movies, Music & Books", "Movies, Music & Books"),
    ("Baby", "Baby"),
    ("Patio & Garden", "Patio & Garden"),
    ("Food, Household & Pets", "Food, Household & Pets"),
    ("Pharmacy, Health & Personal Care", "Pharmacy, Health & Personal Care"),
    ("Beauty", "Beauty"),
    ("Sports, Fitness & Outdoors", "Sports, Fitness & Outdoors"),
    ("Auto, Tires & Industrial", "Auto, Tires & Industrial"),
    ("Photo & Personalized Shop", "Photo & Personalized Shop"),
    ("Art, Craft, Sewing & Party Supplies", "Art, Craft, Sewing & Party Supplies"),
]